Update the guide for outdated instructions
OpenLiberty/guide-cloud-aws pull request #224
Opened 2024-10-21 14:31 UTC by shin19991207

Addressed https://github.com/OpenLiberty/guide-cloud-aws/issues/223

2024-10-28 22:05 UTC, Ruilin-Ma approved these changes
LGTM, thanks!

2024-10-29 17:28 UTC, dmuelle requested changes
ID review: a few minor suggestions

2024-10-29 17:28 UTC, dmuelle commented on README.adoc
> +Before you configure the AWS CLI, you need to create an AWS Identity and Access Management (IAM) user. Navigate to the https://console.aws.amazon.com/iam/home#/users[Identity and Access Management^]
```suggestion
Before you configure the AWS CLI, you need to create an AWS Identity and Access Management (IAM) user. Navigate to the https://console.aws.amazon.com/iam/home#/users[Identity and Access Management^] users dashboard and create a user through the UI. When you create the user, select `programmatic access` as the AWS access type. You will be prompted to set permissions for the user. To complete this guide, the created user must have the following minimal access levels:
```

2024-10-29 17:28 UTC, dmuelle commented on README.adoc
> +Make sure to take note of the `AWS Access Key ID` and `AWS Secret Access Key`, as you will need these to configure the AWS CLI. After the AWS CLI is installed, configure it by running the `aws config
```suggestion
Make sure to copy the `AWS Access Key ID` and `AWS Secret Access Key` values, as you will need these to configure the AWS CLI. After the AWS CLI is installed, configure it by running the `aws configure` command. You will be prompted to provide the `AWS Access Key ID` and `AWS Secret Access Key` values that are associated with the IAM user you created.
```

2024-10-29 17:54 UTC, dmuelle approved these changes
LGTM thanks

2024-10-29 17:55 UTC, merged